# Generated by Django 6.0.1 on 2026-02-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscategorie',
            old_name='categories',
            new_name='categorie',
        ),
    ]
