# Generated by Django 6.0.1 on 2026-02-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_categories_souscategorie_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('motpass', models.CharField(max_length=4)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
