# Generated by Django 6.0.1 on 2026-01-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='statut',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('desactive', 'Desactive'), ('suprime', 'Suprime')], default='actif', max_length=10),
        ),
    ]
